"""add field level user

Revision ID: fa2ef4a949cb
Revises: 77b435a042a5
Create Date: 2021-09-25 21:23:18.477794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa2ef4a949cb'
down_revision = '77b435a042a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('level', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'level')
    # ### end Alembic commands ###
